import type { Metadata } from "next";
import { Geist as GeistFont, Geist_Mono as GeistMonoFont } from "next/font/google";
import "./globals.css";

const geistSans = GeistFont({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = GeistMonoFont({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} bg-black text-gray-200 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
